import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>My First NextJS App</h1>
          <nav>
            <Link href="/">หน้าแรก</Link> |{" "}
            <Link href="/about">เกี่ยวกับเรา</Link> |{" "}
            <Link href="/contact">ติดต่อเรา</Link> |{" "}
          </nav>
        </header>
        <main>{children}</main>
        <footer style={{ marginTop: "2rem", textAlign: "center" }}>
          <p>© 2025 My Website</p>
        </footer>
      </body>
    </html>
  );
}
